Delay = 500
Command = 'python ./pytest.py'
WatchFiles = ['py']
IgnoreFolders = ['node_modules', 'vendor', '.git', '.idea', '.vscode', 'log', 'build', 'dist', 'bin', 'public', 'target', 'output']
ShowEvent = false
Github = 'https://github.com/KM911/hotpot'
